eat-mou/src/App.js

Dear Master

---

eat-mou/src/components/UI/Card.css
eat-mou/src/components/UI/Card.js

[ADD] Card

---

eat-mou/package-lock.json
eat-mou/src/App.js
eat-mou/src/components/Dangol/DangolItem.js

[ADD] 단골아이템 추가및 app에 연동

---

eat-mou/src/components/Location/Location.js
eat-mou/src/components/Location/LocationKitchenList.js

[ADD] LocationKitchenList 추가

---

eat-mou/src/components/Location/Location.js
eat-mou/src/components/Location/LocationKitchenList.js

[FIX] KitchenList 수정

---

eat-mou/src/components/App.js
eat-mou/src/store/index.js

[FIX] 아주 개같은 리렌더링 때문에 더미데이터를 initialState에 박아버렸지 뭐얌~

---

eat-mou/src/Router.js

[ADD] KitchenAdd 라우터 추가

---

eat-mou/src/components/Add/KitchenAdd.js
eat-mou/src/components/Add/KitchenAdd.module.css
eat-mou/src/components/Location/Location.js
eat-mou/src/components/Location/Location.module.css

[ADD] KichenAdd form 및 css 추가

---

eat-mou/package-lock.json
eat-mou/package.json
eat-mou/src/components/Location/Location.js
eat-mou/src/components/Location/Location.module.css
eat-mou/src/components/Location/LocationKitchenList.js
eat-mou/src/components/Location/LocationKitchenList.module.css

[FIX] Location css 수정

---

eat-mou/src/components/UI/Card.js

[FIX] Card span에서 div로 변경

---

eat-mou/src/components/Dangol/DangolItem.js
eat-mou/src/components/Search/Search.js
eat-mou/src/components/Search/SearchKitchenList.js

[ADD] App->Input 값넘어오기 /찜기능 연동되서 찜했으면 Search에서 바로검색해도 한걸로 표시

[ADD] App->Input 값넘어오기 /찜기능 연동되서 찜했으면 Search에서 바로검색해도 한걸로 표시

---

eat-mou/src/components/Search/Search.js

[ADD] firebase에서 정보가져와서 Search에  적용하기

[ADD] firebase에서 정보가져와서 Search에  적용하기

---

eat-mou/src/components/Location/Location.js

[ADD] Location firebase에서 Get기능 추가

[ADD] Location firebase에서 Get기능 추가

---

eat-mou/src/components/Add/KitchenAdd.js
eat-mou/src/components/Add/KitchenAdd.module.css

[FIX] Add css 수정

---

eat-mou/src/components/Search/Search.js
eat-mou/src/components/Search/Search.module.css
eat-mou/src/components/Search/SearchKitchenList.js
eat-mou/src/components/Search/SearchKitchenList.module.css

[ADD] Search 페이지 CSS추가

---

eat-mou/src/components/Dangol/DangolItem.js
eat-mou/src/components/Search/Search.js
eat-mou/src/components/Search/SearchKitchenList.js

[FIX]아무것도 없는 undefined를 map할경우 예외처리

[FIX]아무것도 없는 undefined를 map할경우 예외처리

---

eat-mou/src/components/Search/SearchKitchenList.module.css

[ADD] media 카레

---

eat-mou/src/components/Add/FoodList.js
eat-mou/src/components/Add/InputBox.js
eat-mou/src/components/Add/KitchenAdd.js

[FIX] 오늘의 메뉴 추가 버튼을 누르면 파이어베이스로 넘어가지는 오류 수정

[FIX] 오늘의 메뉴 추가 버튼을 누르면 파이어베이스로 넘어가지는 오류 수정

---

eat-mou/src/components/Add/KitchenAdd.js

[ADD] 오늘의 메뉴 파이어베이스 연결

---

eat-mou/src/components/Add/KitchenAdd.js
eat-mou/src/components/Add/KitchenAdd.module.css

[ADD] KitchenAdd 사진 업로드 css 추가

[ADD] KitchenAdd 사진 업로드 css 추가

---

eat-mou/src/components/Add/Food.js
eat-mou/src/components/Add/FoodList.js
eat-mou/src/components/Add/InputBox.js
eat-mou/src/components/Add/KitchenAdd.module.css

[ADD] KitchenAdd 오늘의 반찬 삭제 기능 추가

[ADD] KitchenAdd 오늘의 반찬 삭제 기능 추가

---

eat-mou/src/components/Add/Food.js
eat-mou/src/components/Add/Food.module.css
eat-mou/src/components/Add/InputBox.js
eat-mou/src/components/Add/InputBox.module.css
eat-mou/src/components/Add/KitchenAdd.js
eat-mou/src/components/Add/KitchenAdd.module.css

[ADD] KitchenAdd 오늘의 메뉴 css 추가

[ADD] KitchenAdd 오늘의 메뉴 css 추가

---

eat-mou/src/components/Location/Location.module.css

[FIX] Location select 화살표 css 수정

[FIX] Location select 화살표 css 수정

---

eat-mou/src/components/Search/Search.js
eat-mou/src/components/Search/SearchKitchenList.js

[FIX] 새로운 데이터  에러 해결및 DB ID설정

---

eat-mou/src/components/Search/SearchKitchenList.js

[FIX] today값이 undefined시 에러상황

---

eat-mou/src/components/Search/SearchKitchenList.js

[FIX] 다중 단골추가하기

---

eat-mou/src/components/Search/SearchKitchenList.js

[FIX] 단골 다중 삭제

---

eat-mou/src/components/Dangol/DangolList.js

[FIX] 서동수 코드에 따른 변경사항

---

eat-mou/src/components/Add/KitchenAdd.js
eat-mou/src/components/Add/KitchenAdd.module.css

[ADD] 유효성 검사 기능 추가

---

eat-mou/src/components/Location/Location.js
eat-mou/src/components/Location/LocationKitchenList.js
eat-mou/src/components/Location/LocationKitchenList.module.css

[ADD] Location 카드 클릭시 info로 이동

[ADD] Location 카드 클릭시 info로 이동

---

eat-mou/src/components/Add/InputBox.module.css
eat-mou/src/components/Add/KitchenAdd.module.css
eat-mou/src/components/Location/Location.module.css

[FIX] 기타 css 수정

---

eat-mou/src/components/Add/KitchenAdd.js
eat-mou/src/components/Location/Location.js

[ADD] Location 거리 정렬되서 나오기

---

eat-mou/src/components/Search/Search.js
eat-mou/src/components/Search/SearchKitchenList.js

[FIX] 거리순 단골순 undefined는 0값으로 처리

[FIX] 거리순 단골순 undefined는 0값으로 처리
